### ISSUE TITLE
Navigation Background

### ISSUE THREAD

**Issue by hend0298** [hend0298/animal-rescue-website#1]
@charlie-quinn For the blue swirl BG on the navigation, I can't seem to get it on top of the banner image. How could I do that?

**Comment by charlie-quinn** [comment]
I'll take a look at this later tonight. 👀

**Comment by charlie-quinn** [comment]
Hey @hend0298 I wasn't sure what you meant by `on top of the banner image` but here are my thoughts:

1. Change doggy image to background image.
2. Put swirl within the doggy image's containing div.
3. Put "our favourite breed" text within the containing div as well.

**Comment by charlie-quinn** [comment]
Also, change your blue swirl image into an SVG so it's transparent 👍

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`
