### ISSUE TITLE
Performance, Accessibility, Browser Testing

### ISSUE THREAD

**Issue by hend0298** [hend0298/animal-rescue-website#2]
@charlie-quinn 

https://docs.google.com/spreadsheets/d/11EKJhUk23sZAx4t3jKqHBvd7bQY2PdjPVmfaCfXhZmM/edit?usp=sharing

**Comment by charlie-quinn** [comment]
✅ `This portion of your final assignment has been graded.`

⚠️`Reminder: please close this issue once it has been resolved.`
